[theme]
primaryColor = "#2E8B57"              # Dark green (buttons, highlights)
backgroundColor = "#f4f9f4"           # Light greenish-white background
secondaryBackgroundColor = "#e0f2e0"  # Softer green for widgets
textColor = "#1a1a1a"                 # Dark grey text
font = "sans serif"
